app:
  work_dir: ./data
  proxy: ''
  host: 127.0.0.1
  port: 5000
youtube:
  sources:
  - url: https://www.youtube.com/watch?v=PpjP_BX5rYE&list=PL1SlIrw0BFdWvS_caZufplFSRF5KhsyVU&index=6
    type: playlist
    title: KTM Big Single Project
ffmpeg:
  bin_path: ffmpeg
  intro_video_path: ./assets/intro.mp4
bilibili:
  tid: 233
  desc_prefix: '本视频搬运自YouTube。

    原视频链接：{youtube_url}


    '
