app:
  work_dir: ./data
  proxy: ''
  host: 127.0.0.1
  port: 5000
youtube:
  sources:
  - url: https://www.youtube.com/watch?v=paA9Z0-_Cao
    type: video
    title: RARE 56 YEAR OLD FLAIL MOWER RESTORATION
ffmpeg:
  bin_path: ffmpeg
  intro_video_path: ./assets/intro.mp4
bilibili:
  tid: 176
  desc_prefix: '本视频搬运自YouTube。

    原视频链接：{youtube_url}


    '
